package com.example.employee.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;

// @Entity: Maps this class to a database table
// @Table(name="employees"): Maps to the 'employees' table in SQL Server
@Entity
@Table(name = "employees")
public class Employee {

    // PRIMARY KEY — auto-generated by SQL Server IDENTITY(1,1)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // NAME — cannot be blank, must be 3–100 characters
    @NotBlank(message = "Name is mandatory")
    @Size(min = 3, max = 100, message = "Name must be between 3 and 100 characters")
    private String name;

    // EMAIL — cannot be blank, must be valid email format
    @NotBlank(message = "Email is mandatory")
    @Email(message = "Invalid email format")
    private String email;

    // SALARY — cannot be null, must be greater than 0
    @NotNull(message = "Salary cannot be null")
    @DecimalMin(value = "0.0", inclusive = false, message = "Salary must be greater than 0")
    private Double salary;

    // DEPARTMENT — cannot be blank
    @NotBlank(message = "Department is mandatory")
    private String department;

    // =========== CONSTRUCTORS ===========

    // Default constructor (required by JPA)
    public Employee() {}

    // Parameterized constructor (for convenience)
    public Employee(String name, String email, Double salary, String department) {
        this.name = name;
        this.email = email;
        this.salary = salary;
        this.department = department;
    }

    // =========== GETTERS AND SETTERS ===========

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public Double getSalary() { return salary; }
    public void setSalary(Double salary) { this.salary = salary; }

    public String getDepartment() { return department; }
    public void setDepartment(String department) { this.department = department; }

    // =========== toString (for debugging) ===========
    @Override
    public String toString() {
        return "Employee{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", salary=" + salary +
                ", department='" + department + '\'' +
                '}';
    }
}
